version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy
          command: ./scripts/deploy-ci.sh

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
