version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.1

jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/app
    steps:
      - kube-orb/install-kubectl
      - checkout
      - run:
          name: Deploy
          command: sh scripts/deploy-ci.sh

workflows:
  version: 2
  build-master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
