version: 2.1

jobs:
  build:
    docker:
      - image: circleci/kubernetes@0.11.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy
          command: sh scripts/deploy-ci.sh

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
