---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: nhood-prod
subjects:
  - kind: ServiceAccount
    name: cicd
    namespace: nhood-prod
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io
