---
apiVersion: v1
kind: Service
metadata:
  name: nhood-service
  namespace: nhood-prod
spec:
  type: LoadBalancer
  selector:
    app: nhood-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
